#!/usr/bin/env bash
set -euo pipefail

# imsg-gtk Linux installer
# Generated by imsg-bridge setup.sh on macOS

INSTALL_DIR="$HOME/.local/share/imsg-gtk"
CONFIG_DIR="$HOME/.config/imsg-gtk"
VENV_DIR="$INSTALL_DIR/.venv"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DESKTOP_DIR="$HOME/.local/share/applications"
BIN_DIR="$HOME/.local/bin"
GLOBAL_BIN="/usr/local/bin/imsg-gtk"
ICON_DIR="$HOME/.local/share/icons/hicolor/scalable/apps"

run_sudo() {
    if [[ "$EUID" -eq 0 ]]; then
        "$@"
        return
    fi

    if [[ -n "${IMSG_SUDO_PASSWORD:-}" ]]; then
        printf '%s\n' "$IMSG_SUDO_PASSWORD" | sudo -S -p '' "$@"
    else
        sudo "$@"
    fi
}

echo "=== imsg-gtk installer ==="
echo ""

# Check for config.json (should be bundled by setup.sh --deploy-*)
if [[ -f "$SCRIPT_DIR/config.json" ]]; then
    CONFIG_SOURCE="$SCRIPT_DIR/config.json"
elif [[ -f "$CONFIG_DIR/config.json" ]]; then
    CONFIG_SOURCE=""
    echo "Using existing config at $CONFIG_DIR/config.json"
else
    echo "ERROR: No config.json found. Re-run setup.sh --deploy-usb or --deploy-ssh on the Mac."
    exit 1
fi

# Install system dependencies
echo "Installing system packages..."
if command -v apt-get &>/dev/null; then
    run_sudo env DEBIAN_FRONTEND=noninteractive NEEDRESTART_MODE=a apt-get update -qq
    run_sudo env DEBIAN_FRONTEND=noninteractive NEEDRESTART_MODE=a \
        apt-get install -y -qq python3 python3-venv python3-gi python3-gi-cairo \
        gir1.2-gtk-4.0 gir1.2-adw-1 libcairo2-dev
elif command -v dnf &>/dev/null; then
    run_sudo dnf install -y python3 python3-gobject gtk4 libadwaita
else
    echo "WARNING: Unsupported package manager. Install manually:"
    echo "  python3, python3-gi, gir1.2-gtk-4.0, gir1.2-adw-1"
fi

# Create install directory
echo "Installing to $INSTALL_DIR..."
mkdir -p "$INSTALL_DIR"
rm -rf "$INSTALL_DIR/imsg_gtk"
cp -r "$SCRIPT_DIR/imsg_gtk" "$INSTALL_DIR/imsg_gtk"
if [[ -f "$SCRIPT_DIR/pyproject.toml" ]]; then
    cp "$SCRIPT_DIR/pyproject.toml" "$INSTALL_DIR/pyproject.toml"
fi

# Create venv with system site packages (for PyGObject)
echo "Creating Python venv..."
python3 -m venv --system-site-packages "$VENV_DIR"
"$VENV_DIR/bin/pip" install --quiet aiohttp

# Copy config
mkdir -p "$CONFIG_DIR"
if [[ -n "${CONFIG_SOURCE:-}" ]]; then
    cp "$CONFIG_SOURCE" "$CONFIG_DIR/config.json"
    echo "Config written to $CONFIG_DIR/config.json"
fi

# Create launcher script
mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/imsg-gtk" <<LAUNCHER
#!/usr/bin/env bash
INSTALL_DIR="$INSTALL_DIR"
VENV_DIR="$VENV_DIR"
export PYTHONPATH="\$INSTALL_DIR\${PYTHONPATH:+:\$PYTHONPATH}"
cd "\$INSTALL_DIR" || exit 1
exec "\$VENV_DIR/bin/python3" -m imsg_gtk.app "\$@"
LAUNCHER
chmod +x "$BIN_DIR/imsg-gtk"

# Install a global launcher when possible so `imsg-gtk` works without ~/.local/bin in PATH
if [[ -w "/usr/local/bin" ]] || command -v sudo &>/dev/null; then
    if run_sudo ln -sf "$BIN_DIR/imsg-gtk" "$GLOBAL_BIN" 2>/dev/null; then
        echo "Global launcher installed at $GLOBAL_BIN"
    else
        echo "WARNING: Could not install global launcher at $GLOBAL_BIN"
    fi
fi

# Validate import path early so launcher failures are caught during install
if ! PYTHONPATH="$INSTALL_DIR" "$VENV_DIR/bin/python3" -c "import imsg_gtk.app" >/dev/null 2>&1; then
    echo "ERROR: Failed to import imsg_gtk.app after installation."
    echo "Check Python/GTK dependencies and rerun install."
    exit 1
fi

# Install app icon (iMessage-style)
DESKTOP_ICON="chat"
if [[ -f "$INSTALL_DIR/imsg_gtk/icon.svg" ]]; then
    mkdir -p "$ICON_DIR"
    cp "$INSTALL_DIR/imsg_gtk/icon.svg" "$ICON_DIR/imsg-gtk.svg"
    DESKTOP_ICON="imsg-gtk"
fi

# Create .desktop entry
mkdir -p "$DESKTOP_DIR"
cat > "$DESKTOP_DIR/imsg-gtk.desktop" <<DESKTOP
[Desktop Entry]
Type=Application
Name=iMessage
Comment=iMessage client for Linux
Exec=$BIN_DIR/imsg-gtk
Icon=$DESKTOP_ICON
Terminal=false
Categories=Network;Chat;InstantMessaging;
Keywords=imessage;chat;messages;
DESKTOP

# Update desktop database if available
if command -v update-desktop-database &>/dev/null; then
    update-desktop-database "$DESKTOP_DIR" 2>/dev/null || true
fi
if command -v gtk-update-icon-cache &>/dev/null; then
    gtk-update-icon-cache -f -t "$HOME/.local/share/icons/hicolor" 2>/dev/null || true
fi

echo ""
echo "=== Installation complete ==="
echo ""
echo "Launch with:  imsg-gtk"
echo "Or find 'iMessage' in your application menu."
echo ""
echo "Config: $CONFIG_DIR/config.json"

# Ensure ~/.local/bin is in PATH
if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
    echo ""
    echo "NOTE: Add ~/.local/bin to your PATH if not already:"
    echo "  echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.bashrc"
fi
