#!/usr/bin/env bash
set -euo pipefail

# imsg-gtk Linux installer
# Generated by imsg-bridge setup.sh on macOS

INSTALL_DIR="$HOME/.local/share/imsg-gtk"
CONFIG_DIR="$HOME/.config/imsg-gtk"
VENV_DIR="$INSTALL_DIR/.venv"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DESKTOP_DIR="$HOME/.local/share/applications"
BIN_DIR="$HOME/.local/bin"

echo "=== imsg-gtk installer ==="
echo ""

# Check for config.json (should be bundled by setup.sh --deploy-*)
if [[ -f "$SCRIPT_DIR/config.json" ]]; then
    CONFIG_SOURCE="$SCRIPT_DIR/config.json"
elif [[ -f "$CONFIG_DIR/config.json" ]]; then
    CONFIG_SOURCE=""
    echo "Using existing config at $CONFIG_DIR/config.json"
else
    echo "ERROR: No config.json found. Re-run setup.sh --deploy-usb or --deploy-ssh on the Mac."
    exit 1
fi

# Install system dependencies
echo "Installing system packages..."
if command -v apt-get &>/dev/null; then
    sudo apt-get update -qq
    sudo apt-get install -y -qq python3 python3-venv python3-gi python3-gi-cairo \
        gir1.2-gtk-4.0 gir1.2-adw-1 libcairo2-dev
elif command -v dnf &>/dev/null; then
    sudo dnf install -y python3 python3-gobject gtk4 libadwaita
else
    echo "WARNING: Unsupported package manager. Install manually:"
    echo "  python3, python3-gi, gir1.2-gtk-4.0, gir1.2-adw-1"
fi

# Create install directory
echo "Installing to $INSTALL_DIR..."
mkdir -p "$INSTALL_DIR"
rm -rf "$INSTALL_DIR/imsg_gtk"
cp -r "$SCRIPT_DIR/imsg_gtk" "$INSTALL_DIR/imsg_gtk"
if [[ -f "$SCRIPT_DIR/pyproject.toml" ]]; then
    cp "$SCRIPT_DIR/pyproject.toml" "$INSTALL_DIR/pyproject.toml"
fi

# Create venv with system site packages (for PyGObject)
echo "Creating Python venv..."
python3 -m venv --system-site-packages "$VENV_DIR"
"$VENV_DIR/bin/pip" install --quiet aiohttp

# Copy config
mkdir -p "$CONFIG_DIR"
if [[ -n "${CONFIG_SOURCE:-}" ]]; then
    cp "$CONFIG_SOURCE" "$CONFIG_DIR/config.json"
    echo "Config written to $CONFIG_DIR/config.json"
fi

# Create launcher script
mkdir -p "$BIN_DIR"
cat > "$BIN_DIR/imsg-gtk" <<LAUNCHER
#!/usr/bin/env bash
exec "$VENV_DIR/bin/python3" -m imsg_gtk.app "\$@"
LAUNCHER
chmod +x "$BIN_DIR/imsg-gtk"

# Create .desktop entry
mkdir -p "$DESKTOP_DIR"
cat > "$DESKTOP_DIR/imsg-gtk.desktop" <<DESKTOP
[Desktop Entry]
Type=Application
Name=iMessage
Comment=iMessage client for Linux
Exec=$BIN_DIR/imsg-gtk
Icon=chat
Terminal=false
Categories=Network;Chat;InstantMessaging;
Keywords=imessage;chat;messages;
DESKTOP

# Update desktop database if available
if command -v update-desktop-database &>/dev/null; then
    update-desktop-database "$DESKTOP_DIR" 2>/dev/null || true
fi

echo ""
echo "=== Installation complete ==="
echo ""
echo "Launch with:  imsg-gtk"
echo "Or find 'iMessage' in your application menu."
echo ""
echo "Config: $CONFIG_DIR/config.json"

# Ensure ~/.local/bin is in PATH
if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
    echo ""
    echo "NOTE: Add ~/.local/bin to your PATH if not already:"
    echo "  echo 'export PATH=\"\$HOME/.local/bin:\$PATH\"' >> ~/.bashrc"
fi
